#train_guardian_model.py (laptop)
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

CSV_FILE = "guardian_training_windows.csv"

FEATURES = [
    "tilt_mean",
    "tilt_max",
    "vibration_mean",
    "vibration_max",
    "shock_mean",
    "shock_peak",
    "sensitivity_mean",
    "n_readings"
]

TARGET = "label"

VALID_LABELS = [
    "SAFE",
    "TILT",
    "VIBRATION",
    "SHOCK"
]


def export_tree_to_micropython(
    model,
    feature_names,
    class_names,
    output_file="guardian_ml_model.py"
):
    tree = model.tree_

    def recurse(node, depth):
        indent = "    " * depth

        # Not a leaf node
        if tree.feature[node] != -2:
            feature_name = feature_names[tree.feature[node]]
            threshold = tree.threshold[node]

            lines = []
            lines.append(f"{indent}if {feature_name} <= {threshold:.6f}:")
            lines.extend(recurse(tree.children_left[node], depth + 1))
            lines.append(f"{indent}else:")
            lines.extend(recurse(tree.children_right[node], depth + 1))
            return lines

        # Leaf node
        class_index = tree.value[node][0].argmax()
        class_label = class_names[class_index]
        return [f'{indent}return "{class_label}"']

    lines = []
    lines.append("# guardian_ml_model.py")
    lines.append("# Auto-generated Decision Tree model for ESP32 MicroPython")
    lines.append("# Generated by train_guardian_model.py")
    lines.append("")
    lines.append("def predict_event(")
    lines.append("    tilt_mean,")
    lines.append("    tilt_max,")
    lines.append("    vibration_mean,")
    lines.append("    vibration_max,")
    lines.append("    shock_mean,")
    lines.append("    shock_peak,")
    lines.append("    sensitivity_mean,")
    lines.append("    n_readings")
    lines.append("):")
    lines.extend(recurse(0, 1))
    lines.append("")
    lines.append("")
    lines.append("def event_to_status(event):")
    lines.append('    if event == "SAFE":')
    lines.append('        return "SAFE"')
    lines.append('    elif event == "TILT":')
    lines.append('        return "WARNING"')
    lines.append('    elif event == "VIBRATION":')
    lines.append('        return "WARNING"')
    lines.append('    elif event == "SHOCK":')
    lines.append('        return "DANGER"')
    lines.append('    else:')
    lines.append('        return "WARNING"')
    lines.append("")

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    print(f"\nMicroPython model exported to: {output_file}")


def clean_dataset(df):
    print("\nOriginal columns:")
    print(list(df.columns))

    # Remove accidental spaces from column names
    df.columns = [c.strip() for c in df.columns]

    # Check required columns
    required_columns = FEATURES + [TARGET]
    missing_columns = [col for col in required_columns if col not in df.columns]

    if missing_columns:
        print("\nMissing required columns:")
        print(missing_columns)
        print("\nAvailable columns:")
        print(list(df.columns))
        return None

    # Remove rows with missing feature or label values
    df = df.dropna(subset=required_columns)

    # Keep only actual training labels
    df[TARGET] = df[TARGET].astype(str).str.strip().str.upper()
    df = df[df[TARGET].isin(VALID_LABELS)]

    # Convert feature columns into numbers
    for col in FEATURES:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.dropna(subset=FEATURES)

    return df


def main():
    df = pd.read_csv(CSV_FILE)

    print("\nLoaded data preview:")
    print(df.head())

    print("\nRaw dataset size:", len(df))

    df = clean_dataset(df)

    if df is None:
        return

    print("\nCleaned dataset size:", len(df))

    print("\nLabel counts:")
    print(df[TARGET].value_counts())

    if len(df) == 0:
        print("\nNo valid training rows found.")
        return

    if len(df[TARGET].unique()) < 2:
        print("\nNeed at least 2 different labels to train.")
        return

    X = df[FEATURES]
    y = df[TARGET]

    model = DecisionTreeClassifier(
        max_depth=4,
        min_samples_leaf=3,
        random_state=42
    )

    # Stratify only works if each class has enough samples
    try:
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.25,
            random_state=42,
            stratify=y
        )
    except ValueError:
        print("\nStratified split failed. Using normal train/test split.")
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.25,
            random_state=42
        )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    print("\nAccuracy:")
    print(accuracy_score(y_test, y_pred))

    print("\nClassification report:")
    print(classification_report(y_test, y_pred))

    print("\nConfusion matrix:")
    print(confusion_matrix(y_test, y_pred, labels=model.classes_))
    print("Labels:", list(model.classes_))

    print("\nDecision tree rules:")
    print(export_text(model, feature_names=FEATURES))

    export_tree_to_micropython(
        model,
        FEATURES,
        model.classes_,
        output_file="guardian_ml_model.py"
    )


if __name__ == "__main__":
    main()
